create table t_municipis (mun_id int generated by default as identity, mun_nom varchar(255), primary key (mun_id));
create table t_persones (per_id int generated by default as identity, per_nom varchar(255), per_munid bigint, primary key (per_id));
create table t_cotxes (cot_matricula varchar(10), cot_model varchar(255), cot_propietari bigint, primary key (cot_matricula));
alter table t_persones add constraint permun_fk foreign key (per_munid) references t_municipis;
alter table t_cotxes add constraint cotper_fk foreign key (cot_propietari) references t_persones;